{{- $files := .Files }}
{{ $serviceName := ( include "myapi.fullname" . )}}
{{ $namespace := .Release.Namespace }}
{{ $port := .Values.service.port | toString }}
{{- range $path, $file := $files.Glob "apidefinitions/*.json" }}
  {{ $basename := base $path }}
  {{ $configMapKey := $basename | trimSuffix ".json" }}
  {{ $content := $file | toString | nindent 4 }}
  {{ $listenPath := include "getServiceUrl" (dict "serviceName" $serviceName "namespace" $namespace "port" $port) }}
  {{ $transformedContent := include "replaceApiListenPath" (dict "apidef" $content "listenPath" $listenPath)}}
  {{ $tykapiname := printf "tykapi-%s" $configMapKey }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $tykapiname }}
data:
  {{ $configMapKey }}: |-
    {{ $transformedContent }}
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: {{ $tykapiname }}
spec:
  tykOAS:
    configmapRef:
      name: {{ $tykapiname }}
      keyName: {{ $configMapKey }}
{{- end }}