{{- $files := .Files }}
{{ $serviceName := ( include "myapi.fullname" . )}}
{{ $namespace := .Release.Namespace }}
{{ $port := .Values.service.port | toString }}
{{ $listenPath := .Values.tykapi.listenPath }}
{{- range $path, $file := $files.Glob "schemas/*.graphql" }}
  {{ $basename := base $path }}
  {{ $configMapKey := $basename | trimSuffix ".graphql" }}
  {{ $content := $file | toString | nindent 4 }}
  {{ $targetUrl := include "getServiceUrl" (dict "serviceName" $serviceName "namespace" $namespace "port" $port) }}
  {{ $tykapiname := printf "tykapi-%s" $configMapKey }}
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: {{ $tykapiname }}
spec:
  name: {{ $configMapKey }}
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: {{ $targetUrl }}
    listen_path: {{ $listenPath }}
    strip_listen_path: true
  graphql:
    enabled: true
    version: "2"
    execution_mode: proxyOnly
    schema: |-
      {{ $content | nindent 2 }}
    playground:
      enabled: true
      path: /playground
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: schemas-configmap
data:
  schema.graphql: |-
    {{ $content }}
---
{{- end }}