name: Deploy workflow

on:
    workflow_dispatch:
        inputs:
            apiName:
              description: 'Select API'
              required: true
              default: 'oas-httpbin'
              type: choice
              options:
              - oas-httpbin
            tag:
              description: 'Version Tag'
              required: true
              type: string
    repository_dispatch:
        types: [trigger]

jobs:
    create-or-update-api:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
        - 
            name: Checkout repository
            uses: actions/checkout@v2
        - 
            name: Setup Host Environment
            run: |
                sudo echo "${{ secrets.TYK_DASHBOARD_URL }} tyk-dashboard.org" | sudo tee -a /etc/hosts 
        -
            name: Setup ORAS
            uses: oras-project/setup-oras@v1
        - 
            name: Check if file exists
            id: check-file
            run: |
                if [ -f "./${{ inputs.apiName }}/apidefinitions/${{ inputs.apiName }}.json" ]; then
                    echo "fileExists=true" >> $GITHUB_OUTPUT
                else
                    echo "fileExists=false" >> $GITHUB_OUTPUT
                fi
        -
            name: Read file and extract ID
            if: steps.check-file.outputs.fileExists == 'true'
            id: read-file
            run: |
                json=$(<./${{ inputs.apiName }}/apidefinitions/${{ inputs.apiName }}.json)
                id=$(jq -r '."x-tyk-api-gateway".info.id' <<< "$json")
                echo "id=$id" >> $GITHUB_OUTPUT
        -
            name: Patch or Import API
            env:
                body: ${{ steps.download-openapi.outputs.body }}
                id: ${{ steps.read-file.outputs.id }}
            run: |
                oras pull registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.apiName }}:openapi_schema-${{ inputs.tag }}
                body=$(<openapi_schema.json)

                if [ "${{ steps.check-file.outputs.fileExists }}" == 'true' ]; then
                    # If the file exists, Patch API
                    echo "# Patched API $id ..."
                    wget --method=PATCH http://tyk-dashboard.org/api/apis/oas/$id --header='Authorization: ${{ secrets.TYK_APIKEY }}' --header='Content-Type: text/plain' --body-data="$body" -O res.json
                    api_id=$id
                else
                    # If the file does not exist, Import API
                    echo "# Import API  ..."
                    wget --method=POST http://tyk-dashboard.org/api/apis/oas/import --header='Authorization: ${{ secrets.TYK_APIKEY }}' --header='Content-Type: text/plain' --body-data="$body" -O res.json
                    api_id=$(cat res.json | jq -r '.ID')
                fi

                echo "# "
                echo "# Retrieve API Definition $api_id..."
                echo "# "
                wget --method=GET http://tyk-dashboard.org/api/apis/oas/$api_id --header 'Authorization: ${{ secrets.TYK_APIKEY }}' --header 'Content-Type: text/plain' -O res.json

                cat res.json | jq '."x-tyk-api-gateway".server.listenPath.value="<<AUTO REPLACE LISTENPATH>>"' | jq '."x-tyk-api-gateway".upstream.url="<<AUTO REPLACE TARGETURL>>"' > ${{ inputs.apiName }}.json

                # echo "# "
                # echo "# Remove Temporary API $api_id ..."
                # echo "# "
                # wget --method=DELETE http://tyk-dashboard.org/api/apis/oas/$api_id --header 'Authorization: ${{ secrets.TYK_APIKEY }}' -O res.json

                rm res.json

                mv ./${{ inputs.apiName }}.json ./${{ inputs.apiName }}/apidefinitions/${{ inputs.apiName }}.json

                echo "# "
                echo "# Generated API Definition ... ./${{ inputs.apiName }}/apidefinitions/${{ inputs.apiName }}.json "
                echo "# "
                cat ./${{ inputs.apiName }}/apidefinitions/${{ inputs.apiName }}.json
        - 
            name: Update values.yaml
            run: |
                new_tag="${{ inputs.tag }}"  # Set your new tag value here
                sed "s/\(tag: \).*/\1$new_tag/" ./${{ inputs.apiName }}/values.yaml > ./tmp.yaml
                cp ./tmp.yaml ./${{ inputs.apiName }}/values.yaml
                rm ./tmp.yaml
        -
            name: Commit API Definition file and values.yaml
            run: |
                git config --global user.name 'github action'
                git config --global user.email 'github_action@tyk.com'
                git add ./${{ inputs.apiName }}/apidefinitions/${{ inputs.apiName }}.json
                git add ./${{ inputs.apiName }}/values.yaml
                git commit -m "Update API Definition by release action"
                git push